### ISSUE TITLE
canny_edges function works for a long time

### ISSUE THREAD

**Issue by Jekahome** [rust-cv/ndarray-vision#28]
Your example ndarray-vision/examples/edges.rs  built canny in 36 seconds
    Library imageproc built canny in 2 seconds 

``` 
    let now = std::time::Instant::now();
    let im = image::open("images/lena.png").unwrap().to_luma();
    imageproc::edges::canny(&im, 1.0, 30.0).save("images/lena-canny.png");
    println!("{} sec", now.elapsed().as_secs());// 2 sec !!!
```

**Comment by xd009642** [comment]
I'll hopefully have a look at the weekend, I haven't explicitly worked to optimise anything although the latest changes (not yet released) offer some performance improvements.

Also, did you run in release?

**Comment by xd009642** [comment]
Never mind I've started working on a ndarray-vision benchmarking repo comparing it to imageproc (and some other crates in future) and have recreated numbers similar to your PR. I'll work on speeding it up this weekend

**Comment by xd009642** [comment]
Right so a lot of the issue was using the ndarray arithmetic ops to implement the primitives. While it does result in more concise code it does create a lot more owned arrays. I've removed it from the sobel and convolution mostly and now the canny is just 3x slower instead of 18x slower. I've got some other improvements to image padding that should do the rest of the speedup

**Comment by xd009642** [comment]
Okay the canny function still isn't as fast as imageproc but it's significantly faster than it was previously. I'm going to put out a new release now and close this issue
